/**
 * What the ledger actually holds, straight out of whatever `DATABASE_URL` points at.
 *
 * The export sitting in `docs/source/` is not evidence that it was ever imported,
 * and a refresh that writes before anybody looked cannot say afterwards what it
 * changed. So this runs first, it reads and never writes — every statement here is
 * a `select` — and its output is committed beside the export as the *before*.
 *
 * It prints Markdown on stdout and nothing else, so the record is made by
 * redirecting it:
 *
 *   npm run db:census > docs/source/ledger-census.md
 *
 * The connection string is never printed; the host is, so the record says which
 * database it describes.
 */

import pg from "pg";

interface PersonRow {
  readonly id: string;
  readonly display_name: string;
}

interface CategoryRow {
  readonly person_id: string;
  readonly type: string;
  readonly total: string;
  readonly retired: string;
}

interface MonthRow {
  readonly person_id: string;
  readonly year: number;
  readonly month: number;
  readonly type: string;
  readonly entries: string;
  readonly amount_minor: string;
  readonly currency: string;
}

interface SpanRow {
  readonly entries: string;
  readonly categories: string;
  readonly first_month: string | null;
  readonly last_month: string | null;
}

const HEBREW_MONTHS = [
  "ינואר",
  "פברואר",
  "מרץ",
  "אפריל",
  "מאי",
  "יוני",
  "יולי",
  "אוגוסט",
  "ספטמבר",
  "אוקטובר",
  "נובמבר",
  "דצמבר",
] as const;

/** Minor units to a plain decimal string. The census states figures, never sums them. */
function decimals(minor: string): string {
  const value = BigInt(minor);
  const negative = value < 0n;
  const digits = (negative ? -value : value).toString().padStart(3, "0");
  const whole = digits.slice(0, -2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  return `${negative ? "−" : ""}${whole}.${digits.slice(-2)}`;
}

const connectionString = process.env.DATABASE_URL;
if (connectionString === undefined || connectionString.length === 0) {
  throw new Error(
    "DATABASE_URL is not set. Pull it with `npx vercel env pull .env.production.local`, " +
      "or set it in the environment before running this.",
  );
}

const local = /@(localhost|127\.0\.0\.1)[:/]/.test(connectionString);

const client = new pg.Client({
  connectionString,
  ssl: local ? false : { rejectUnauthorized: true },
});

await client.connect();

const lines: string[] = [];
const say = (line = "") => lines.push(line);

try {
  const people = (await client.query<PersonRow>(`select id, display_name from people order by id`)).rows;

  const span = (
    await client.query<SpanRow>(`
      select count(*)::text                                          as entries,
             count(distinct personal_category_id)::text              as categories,
             min(to_char(make_date(year, month, 1), 'YYYY-MM'))      as first_month,
             max(to_char(make_date(year, month, 1), 'YYYY-MM'))      as last_month
        from entries
    `)
  ).rows[0];

  const categories = (
    await client.query<CategoryRow>(`
      select person_id,
             type,
             count(*)::text                                             as total,
             count(*) filter (where active_until is not null)::text      as retired
        from personal_categories
       group by person_id, type
       order by person_id, type
    `)
  ).rows;

  const months = (
    await client.query<MonthRow>(`
      select c.person_id,
             e.year,
             e.month,
             c.type,
             count(*)::text        as entries,
             sum(e.amount_minor)::text as amount_minor,
             min(e.currency)       as currency
        from entries e
        join personal_categories c on c.id = e.personal_category_id
       group by c.person_id, e.year, e.month, c.type
       order by e.year, e.month, c.person_id, c.type
    `)
  ).rows;

  const households = (
    await client.query<{ count: string }>(`select count(*)::text as count from household_categories`)
  ).rows[0];

  say(`<!--`);
  say(`  Generated by \`npm run db:census\`. Read-only: every statement in`);
  say(`  scripts/ledger-census.ts is a select.`);
  say(`-->`);
  say();
  say(`# מאזן — what the database holds`);
  say();
  say(`- Host: \`${new URL(connectionString).host}\``);
  say(`- Taken: ${new Date().toISOString().slice(0, 10)}`);
  say(`- People: ${people.map((person) => `${person.display_name} (${person.id})`).join(", ")}`);
  say(`- Household categories: ${households?.count ?? "0"}`);
  say(
    `- Entries: ${span?.entries ?? "0"} across ${span?.categories ?? "0"} personal categories` +
      (span?.first_month != null ? `, ${span.first_month} – ${span.last_month}` : ""),
  );
  say();

  say(`## Personal categories`);
  say();
  say(`| Person | Type | Total | Retired |`);
  say(`| --- | --- | ---: | ---: |`);
  for (const row of categories) {
    say(`| ${row.person_id} | ${row.type} | ${row.total} | ${row.retired} |`);
  }
  say();

  say(`## Entries by month`);
  say();
  say(`One row per calendar month. A month absent from this table holds nothing at all.`);
  say();

  const personIds = people.map((person) => person.id);
  const header = personIds.flatMap((id) => [`${id} הכנסות`, `${id} הוצאות`, `${id} #`]);
  say(`| חודש | ${header.join(" | ")} |`);
  say(`| --- | ${header.map(() => "---:").join(" | ")} |`);

  const byMonth = new Map<string, MonthRow[]>();
  for (const row of months) {
    const key = `${row.year}-${String(row.month).padStart(2, "0")}`;
    byMonth.set(key, [...(byMonth.get(key) ?? []), row]);
  }

  for (const [key, rows] of [...byMonth.entries()].sort(([left], [right]) => left.localeCompare(right))) {
    const monthIndex = Number(key.slice(5)) - 1;
    const cells = personIds.flatMap((id) => {
      const income = rows.find((row) => row.person_id === id && row.type === "income");
      const expense = rows.find((row) => row.person_id === id && row.type === "expense");
      const count = Number(income?.entries ?? 0) + Number(expense?.entries ?? 0);
      return [
        income === undefined ? "—" : decimals(income.amount_minor),
        expense === undefined ? "—" : decimals(expense.amount_minor),
        count === 0 ? "—" : String(count),
      ];
    });
    say(`| ${key} ${HEBREW_MONTHS[monthIndex] ?? ""} | ${cells.join(" | ")} |`);
  }

  process.stdout.write(`${lines.join("\n")}\n`);
} finally {
  await client.end();
}
